# Generated by Django 3.2.2 on 2021-05-13 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('introduction', models.TextField(blank=True, default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('valid_time', models.DateTimeField(null=True)),
                ('room_type', models.CharField(choices=[('public', '公開房間'), ('private', '私密房間'), ('course', '課程討論房間')], default='public', max_length=10)),
                ('room_category', models.CharField(choices=[('course', '課程討論'), ('find_group', '尋求組隊')], default='course', max_length=20)),
                ('people_limit', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('access_level', models.CharField(choices=[('admin', '房主'), ('manager', '管理員'), ('user', '一般成員')], default='user', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='room.room')),
            ],
        ),
    ]
