# Generated by Django 3.2.2 on 2021-05-25 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('introduction', models.TextField(blank=True, default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('valid_time', models.DateTimeField(null=True)),
                ('room_type', models.CharField(choices=[('public', '公開房間'), ('private', '私密房間'), ('course', '課程討論房間')], default='public', max_length=10)),
                ('room_category', models.CharField(choices=[('course', '課程討論'), ('find_group', '尋求組隊')], default='course', max_length=20)),
                ('people_limit', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('record', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('access_level', models.CharField(choices=[('admin', '房主'), ('manager', '管理員'), ('user', '一般成員')], default='user', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='room.room')),
            ],
            options={
                'unique_together': {('room', 'member')},
            },
        ),
        migrations.CreateModel(
            name='RoomInvitingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('open', 'open')], default='open', max_length=10)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_request_list', to='room.room')),
            ],
            options={
                'unique_together': {('room', 'request_user')},
            },
        ),
        migrations.CreateModel(
            name='RoomInviting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('open', 'open')], default='open', max_length=10)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_list', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_list', to='room.room')),
            ],
            options={
                'unique_together': {('room', 'invited')},
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=50)),
                ('block_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_blocked_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to='room.room')),
            ],
            options={
                'unique_together': {('room', 'blocked_user')},
            },
        ),
    ]
