# Generated by Django 3.2.2 on 2021-05-16 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInviting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_time', models.DateTimeField(auto_now_add=True)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_list', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_list', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=50)),
                ('block_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to=settings.AUTH_USER_MODEL)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_blocked_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to='room.room')),
            ],
        ),
    ]
