# Generated by Django 3.2 on 2021-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='valid_time',
            field=models.DateTimeField(null=True),
        ),
    ]
