# Generated by Django 3.2.2 on 2021-05-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrecord',
            old_name='record',
            new_name='recording',
        ),
    ]
