# Generated by Django 3.2.2 on 2021-05-19 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_roomblock_roominviting_roomrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrecord',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roommember',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='roomblock',
            unique_together={('room', 'blocked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='roominviting',
            unique_together={('room', 'invited')},
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('room', 'member')},
        ),
        migrations.CreateModel(
            name='RoomInvitingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_list', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_request_list', to='room.room')),
            ],
            options={
                'unique_together': {('room', 'request_user')},
            },
        ),
    ]
