# Generated by Django 3.2.2 on 2021-05-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_record_roomrecord_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominviting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roominvitingrequest',
            name='status',
        ),
    ]
