# Generated by Django 3.2 on 2021-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_valid_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('public', '公開房間'), ('private', '私密房間'), ('course', '課程討論房間')], default='public', max_length=10),
        ),
    ]
