# Generated by Django 3.2.2 on 2021-06-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210530_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
