# Generated by Django 3.2.2 on 2021-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210519_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominviting',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('open', 'open')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='roominvitingrequest',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('open', 'open')], default='open', max_length=10),
        ),
    ]
