# Generated by Django 3.2.2 on 2021-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_roommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='nickname',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
