# Generated by Django 3.2.2 on 2021-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_roommessage_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(default='http://123.com'),
            preserve_default=False,
        ),
    ]
