# Generated by Django 3.2.2 on 2021-06-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('course', '課程討論'), ('eating', '吃飯')], default='course', max_length=20),
        ),
    ]
