# Generated by Django 3.2.2 on 2021-06-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_room_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('course', '課程討論'), ('eating', '吃飯'), ('hiking', '爬山')], default='course', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('room', 'nickname')},
        ),
    ]
