# Generated by Django 3.2.2 on 2021-05-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
