# Generated by Django 3.2.2 on 2021-06-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210603_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_token',
        ),
    ]
