# Generated by Django 3.2.2 on 2021-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
