# Generated by Django 3.2.2 on 2021-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', '未讀'), ('read', '已讀')], default='unread', max_length=10),
        ),
    ]
